
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    clean: true
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    # Build and run tests for .NET Desktop or Windows classic desktop solutions.
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'Sql Databases\FD.Internal.Dev\FD.Internal.Dev\bin\Release\'
    ArtifactName: 'FD.Internal'
    publishLocation: 'Container'
