
CREATE DATABASE [FD.Internal.Dev]  (EDITION = 'Basic', SERVICE_OBJECTIVE = 'Basic', MAXSIZE = 2 GB)
GO

ALTER DATABASE [FD.Internal.Dev] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [FD.Internal.Dev] SET ANSI_NULLS OFF
GO

ALTER DATABASE [FD.Internal.Dev] SET ANSI_PADDING OFF
GO

ALTER DATABASE [FD.Internal.Dev] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [FD.Internal.Dev] SET ARITHABORT OFF
GO

ALTER DATABASE [FD.Internal.Dev] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [FD.Internal.Dev] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [FD.Internal.Dev] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [FD.Internal.Dev] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [FD.Internal.Dev] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [FD.Internal.Dev] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [FD.Internal.Dev] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [FD.Internal.Dev] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [FD.Internal.Dev] SET ALLOW_SNAPSHOT_ISOLATION ON
GO

ALTER DATABASE [FD.Internal.Dev] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [FD.Internal.Dev] SET READ_COMMITTED_SNAPSHOT ON
GO

ALTER DATABASE [FD.Internal.Dev] SET  MULTI_USER
GO

ALTER DATABASE [FD.Internal.Dev] SET ENCRYPTION ON
GO

ALTER DATABASE [FD.Internal.Dev] SET QUERY_STORE = ON
GO

/****** Object:  Table [dbo].[pointMatrix]    Script Date: 2/13/2020 1:48:19 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[points]    Script Date: 2/13/2020 1:48:19 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[pointTypes]    Script Date: 2/13/2020 1:48:19 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[rewardIdeas]    Script Date: 2/13/2020 1:48:19 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[rewards]    Script Date: 2/13/2020 1:48:19 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[userDetails]    Script Date: 2/13/2020 1:48:19 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[userPoints]    Script Date: 2/13/2020 1:48:19 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[userPointsData]    Script Date: 2/13/2020 1:48:19 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER DATABASE [FD.Internal.Dev] SET  READ_WRITE
GO

--Syntax Error: Incorrect syntax near CATALOG_COLLATION.
--WITH CATALOG_COLLATION = SQL_Latin1_General_CP1_CI_AS;

GO

ALTER DATABASE [FD.Internal.Dev] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 7), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 10, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)

GO

--Syntax Error: Incorrect syntax near WAIT_STATS_CAPTURE_MODE.
--ALTER DATABASE [FD.Internal.Dev] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 7), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 10, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)



GO
